In [2]:
import numpy as np

In [4]:
list1 = [1,2,3,4,5]
np_list_1 = np.array(list1)

In [5]:
print(type(list1))
print(type(np_list_1))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
array_2d = np.array([[1,2,3,4],
            [4,5,6,4.2]])

In [10]:
array_2d[1][2]

6

In [12]:
np_list_1.ndim

1

In [15]:
array_2d.shape

(2, 4)

In [49]:
array_2d.reshape((4,2))

array([[1. , 2. ],
       [3. , 4. ],
       [4. , 5. ],
       [6. , 4.2]])

In [26]:
array_2d.dtype

dtype('float64')

In [31]:
array_2d.flatten()

array([1. , 2. , 3. , 4. , 4. , 5. , 6. , 4.2])

In [37]:
nd_list_A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])  

nd_list_B = np.array([
    [1],
    [2],
    [3]
])  


nd_list_identity = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],

])


nd_list_A ** nd_list_B

array([[  1,   2,   3],
       [ 16,  25,  36],
       [343, 512, 729]])

In [38]:
nd_list_A.dot(nd_list_identity)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
nd_list_A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
np.zeros((15,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [43]:
np.ones((15,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [48]:
np.linspace(0,100,27)

array([  0.        ,   3.84615385,   7.69230769,  11.53846154,
        15.38461538,  19.23076923,  23.07692308,  26.92307692,
        30.76923077,  34.61538462,  38.46153846,  42.30769231,
        46.15384615,  50.        ,  53.84615385,  57.69230769,
        61.53846154,  65.38461538,  69.23076923,  73.07692308,
        76.92307692,  80.76923077,  84.61538462,  88.46153846,
        92.30769231,  96.15384615, 100.        ])